[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

[etherscan]
base_georli= { key= "PLACEHOLDER_STRING", url='https://api-goerli.basescan.org'}

[rpc_endpoints]
base_georli = "${BASE_TESTNET_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
